version: "3.7"
services:
  
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:14.0.0
    #environment:
    #  KEYCLOAK_USER: admin
    #  KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"

  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"
  
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.25
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus-ifood
    image: prometheus-ifood
    network_mode: "host"

  grafana_ifood:
    container_name: grafana-ifood
    image: grafana/grafana:6.5.0
    network_mode: "host"

  artemis_ifood:
    container_name: artemis-ifood
    image: vromero/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 8161:8161
      - 5672:5672
      - 61616:61616

  mongodb_ifood:
    container_name: mongodb_ifood
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedido
      MONGO_INITDB_ROOT_PASSWORD: pedido
      MONGO_INITDB_DATABASE: pedido
    ports:
      - 27017:27017

  #Dependência do Kafka
  zookeeper:
    container_name: zookeeper_container
    image: debezium/zookeeper:1.1
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  
  kafka:
    container_name: kafka_container
    image: debezium/kafka:1.1
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     
  #Interface Web para Kafka
  kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
       KAFKA_BROKERCONNECT: kafka:9092
    ports:
     - 9000:9000
    depends_on:
      - kafka
