version: "3.7"
services:
  
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:14.0.0
    #environment:
    #  KEYCLOAK_USER: admin
    #  KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"

  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"
  
  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.25
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus-ifood
    image: prometheus-ifood
    network_mode: "host"

  grafana_ifood:
    container_name: grafana-ifood
    image: grafana/grafana:6.5.0
    network_mode: "host"

  artemis_ifood:
    container_name: artemis-ifood
    image: vromero/activemq-artemis:latest-alpine
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - 8161:8161
      - 61616:61616

