-- public.localizacao definition

-- Drop table

-- DROP TABLE public.tb_localizacao;

CREATE TABLE tb_localizacao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	latitude float8 NULL,
	longitude float8 NULL,
	CONSTRAINT localizacao_pkey PRIMARY KEY (id)
);