version: "3.7"
services:

  #Dependência do Kafka
  zookeeper:
    container_name: zookeeper_container
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    environment:
      LOG_DIR: /tmp/logs
    
  
  kafka:
    container_name: kafka_container
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper    
    ports:
     - 9092:9092
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  #Interface Web para Kafka
  kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.27.0
    environment:
       KAFKA_BROKERCONNECT: kafka:9092
    ports:
     - 9000:9000
    depends_on:
      - kafka